FROM mcr.azure.cn/devcontainers/base:bookworm

RUN apt-get update \
    && apt-get install -y --no-install-recommends mosquitto mosquitto-clients \
    && rm -rf /var/lib/apt/lists/* \
    && mkdir -p /mosquitto/config /mosquitto/data /mosquitto/log \
    && chown -R mosquitto:mosquitto /mosquitto

COPY mosquitto.conf /mosquitto/config/mosquitto.conf
COPY docker-entrypoint.sh /mosquitto/config/docker-entrypoint.sh
RUN chmod +x /mosquitto/config/docker-entrypoint.sh

EXPOSE 1883 9001

ENTRYPOINT ["/mosquitto/config/docker-entrypoint.sh"]
